elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000
    
    computed_torque_controller_clik:
      type: arm_controllers/Computed_Torque_Controller_CLIK
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
        
      gains:
        elfin_joint1: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint2: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint3: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint4: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint5: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint6: 
          pid: {p: 100.0, i: 0, d: 20.0}

      root_link: world
      tip_link: elfin_link6

      ctr_obj: 1  # ctr_obj = 1: Regulation 
                  # ctr_obj = 2: Tracking
                  
      ik_mode: 2 # open-loop inverse kinematics using jacobian
                 # closed-loop inverse Kinematics using jacobian

      clik_gain: {K_regulation: 6.0, K_tracking: 1.0}