acrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Position Controllers ---------------------------------------
  joint1_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint1

  joint2_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint2
